# ConfiguraÃ§Ãµes Gerais
baseur1 = "https://RuiFMLopes.github.io/portfolio/"
title = "Rui FM Lopes"
theme = "hugo-coder"
canonifyURLs = true
relativeURLs = true
languagecode = "pt-pt"
defaultcontentlanguage = "pt-pt"

[languages]
  [languages.pt-pt]
    languageName = "PortuguÃªs ðŸ‡µðŸ‡¹"
    contentDir = "content/pt-pt"
    weight = 1
    [languages.pt-pt.params]
      info = "Estudante de Engenharia InformÃ¡tica"
    [[languages.pt-pt.menu.main]]
      name = "Sobre"
      url = "about/"
      weight = 1
    [[languages.pt-pt.menu.main]]
      name = "Projectos"
      url = "projects/"
      weight = 2
    [[languages.pt-pt.menu.main]]
      name = "Contacto"
      url = "contact/"
      weight = 3


  [languages.en]
    languageName = "English ðŸ‡¬ðŸ‡§"
    contentDir = "content/en"
    weight = 2
    [languages.en.params]
      info = "Computer Science and Engineering Student"
    [[languages.en.menu.main]]
      name = "About"
      url = "about/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Projects"
      url = "projects/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Contact"
      url = "contact/"
      weight = 3
[pagination]
  pagerSize = 20

[markup.highlight]
  style = "github-dark"

[params]
  author = "Rui Filipe Morais Lopes"
 
  description = "PortefÃ³lio profissional de Rui Filipe Morais Lopes"
  keywords = "engenharia, informÃ¡tica, programador"
  avatarurl = "images/avatar.jpg" # Lembra-te de pÃ´r a foto em static/images/avatar.jpg
  
  images = ["images/avatar.jpg"]

  since = 2025
  enableTwemoji = true
  colorScheme = "dark"
  # ForÃ§a o modo escuro como predefiniÃ§Ã£o
  colorProtocol = "dark"
  hidecolorschemetoggle = false
  hideCredits = false
  hideCopyright = false
  hideFooter = false
  
  
  


# Links das Redes Sociais
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/RuiFMLopes/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/rui-filipe-morais-lopes-0a43343a2/" 



